<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="9" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-21T17:02:56 IST" name="Suite" finished-at="2024-01-21T17:03:40 IST" duration-ms="43508">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" name="LoginErrorValidation" class="rahulshettyacadmy.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="PurchaseOrder">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" name="submitOrder" class="rahulshettyacadmy.tests.SubmitOrderTest"/>
      </group> <!-- PurchaseOrder -->
    </groups>
    <test started-at="2024-01-21T17:02:56 IST" name="Submit Order Test" finished-at="2024-01-21T17:03:38 IST" duration-ms="41423">
      <class name="rahulshettyacadmy.tests.SubmitOrderTest">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:02:57 IST" name="lanchApplication" finished-at="2024-01-21T17:03:07 IST" duration-ms="9583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:07 IST" name="submitOrder" data-provider="getData" finished-at="2024-01-21T17:03:15 IST" duration-ms="8208" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pass=Tdata2548, email=tdata2548@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:15 IST" name="tearDown" finished-at="2024-01-21T17:03:15 IST" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:15 IST" name="lanchApplication" finished-at="2024-01-21T17:03:22 IST" duration-ms="6494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:22 IST" name="submitOrder" data-provider="getData" finished-at="2024-01-21T17:03:30 IST" duration-ms="7845" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pass=Iamking@000, email=anshika@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:30 IST" name="tearDown" finished-at="2024-01-21T17:03:31 IST" duration-ms="1014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:31 IST" name="lanchApplication" finished-at="2024-01-21T17:03:36 IST" duration-ms="5275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:36 IST" name="OrderHistoryTest" finished-at="2024-01-21T17:03:37 IST" depends-on-methods="rahulshettyacadmy.tests.SubmitOrderTest.submitOrder" duration-ms="1255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.SubmitOrderTest@466276d8]" started-at="2024-01-21T17:03:37 IST" name="tearDown" finished-at="2024-01-21T17:03:38 IST" duration-ms="397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahulshettyacadmy.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2024-01-21T17:02:56 IST" name="Error Validation Test" finished-at="2024-01-21T17:03:40 IST" duration-ms="43508">
      <class name="rahulshettyacadmy.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:02:56 IST" name="lanchApplication" finished-at="2024-01-21T17:03:06 IST" duration-ms="9572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:06 IST" name="LoginErrorValidation" finished-at="2024-01-21T17:03:09 IST" duration-ms="3347" status="SKIP">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<......> but was:<...or...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<......> but was:<...or...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at rahulshettyacadmy.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:09 IST" name="tearDown" finished-at="2024-01-21T17:03:11 IST" duration-ms="1308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:11 IST" name="lanchApplication" finished-at="2024-01-21T17:03:16 IST" duration-ms="5352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:16 IST" name="LoginErrorValidation" finished-at="2024-01-21T17:03:17 IST" duration-ms="1266" status="SKIP">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<......> but was:<...or...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<......> but was:<...or...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at rahulshettyacadmy.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:17 IST" name="tearDown" finished-at="2024-01-21T17:03:18 IST" duration-ms="396" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:18 IST" name="lanchApplication" finished-at="2024-01-21T17:03:25 IST" duration-ms="7101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:25 IST" name="LoginErrorValidation" finished-at="2024-01-21T17:03:26 IST" duration-ms="1532" status="FAIL">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<......> but was:<...or...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<......> but was:<...or...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at rahulshettyacadmy.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:27 IST" name="tearDown" finished-at="2024-01-21T17:03:27 IST" duration-ms="349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:27 IST" name="lanchApplication" finished-at="2024-01-21T17:03:32 IST" duration-ms="4927" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:32 IST" name="productErrorValidation" finished-at="2024-01-21T17:03:39 IST" duration-ms="7521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacadmy.tests.ErrorValidationsTest@289710d9]" started-at="2024-01-21T17:03:39 IST" name="tearDown" finished-at="2024-01-21T17:03:40 IST" duration-ms="312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahulshettyacadmy.tests.ErrorValidationsTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
